{{- if .Values.ecrRegistryHelper.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hybrid-ingestion-runner.fullname" . }}-ecr-registry-helper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hybrid-ingestion-runner.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
{{- end }}
