{{- if .Values.config.ingestionPods.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hybrid-ingestion-runner.ingestionServiceAccountName" . }}
  labels:
    {{- include "hybrid-ingestion-runner.labels" . | nindent 4 }}
  {{- with .Values.config.ingestionPods.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.config.ingestionPods.serviceAccount.automount }}
{{- end }}
