{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hybrid-ingestion-runner.fullname" . }}
  labels:
    {{- include "hybrid-ingestion-runner.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "hybrid-ingestion-runner.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics-app
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
