{{- if .Values.config.ingestionPods.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hybrid-ingestion-runner.ingestionServiceAccountName" . }}
  labels:
    {{- include "hybrid-ingestion-runner.labels" . | nindent 4 }}
  {{- with .Values.config.ingestionPods.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.config.ingestionPods.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingestion

rules:
{{- if or .Values.argoWorkflows.enabled (ne .Values.config.argoWorkflows.endpoint "") }}
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
{{- end }}
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingestion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingestion
subjects:
- kind: ServiceAccount
  name: {{ include "hybrid-ingestion-runner.ingestionServiceAccountName" . }}
  namespace: {{ include "hybrid-ingestion-runner.namespace" . }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ include "hybrid-ingestion-runner.ingestionServiceAccountName" . }}
  name: {{ include "hybrid-ingestion-runner.ingestionServiceAccountName" . }}.service-account-token
type: kubernetes.io/service-account-token
{{- end }}
