apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybrid-ingestion-runner.fullname" . }}
  labels:
    {{- include "hybrid-ingestion-runner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: app
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics-app
      protocol: TCP
      name: metrics-app
  selector:
    {{- include "hybrid-ingestion-runner.selectorLabels" . | nindent 4 }}
