apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hybrid-ingestion-agent.fullname" . }}
  labels:
    {{- include "hybrid-ingestion-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hybrid-ingestion-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hybrid-ingestion-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hybrid-ingestion-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: 8585
              protocol: TCP
          env:
            - name: ARGO_WORKFLOW_EXECUTOR_SERVICE_ACCOUNT_NAME
              value: {{ include "hybrid-ingestion-agent.ingestionServiceAccountName" . }}
            {{- with .Values.config }}
            - name: AGENT_ID
              value: "{{ .agentId }}"
            - name: AUTH_TOKEN
              value: "{{ .authToken }}"
            - name: SERVER_URL
              value: "{{ .serverUrl }}"
            - name: RECONNECT_DELAY_SECONDS
              value: "{{ .reconnectDelaySeconds }}"
            {{- with .ingestionPods }}
            - name: ARGO_NAMESPACE
              value: "{{ .namespace }}"
            - name: ARGO_INGESTION_IMAGE
              value: "{{ .baseImage }}"
            {{- if .disableVersionValidation }}
            - name: ARGO_DISABLE_VERSION_VALIDATION
              value: "{{ .disableVersionValidation }}"
            {{- end }}
            - name: ARGO_WORKFLOW_CUSTOMER_TOLERATION
              value: "{{ .customerToleration }}"
            - name: ARGO_IMAGE_PULL_SECRETS
              value: "{{ .imagePullSecrets }}"
            - name: ARGO_AUTOMOUNT_SA_TOKEN
              value: "{{ .automountSAToken }}"
            - name: ARGO_EXTRA_ENVS
              value: '[{{ join "," .extraEnvs }}]'
            {{- with .resources.limits }}
            - name: ARGO_WORKFLOW_CPU_LIMIT
              value: "{{ .cpu }}"
            - name: ARGO_WORKFLOW_MEMORY_LIMIT
              value: "{{ .memory }}"
            {{- end }}
            {{- with .resources.requests }}
            - name: ARGO_WORKFLOW_CPU_REQUEST
              value: "{{ .cpu }}"
            - name: ARGO_WORKFLOW_MEMORY_REQUEST
              value: "{{ .memory }}"
            {{- end }}
            {{- with .automationResources.limits }}
            - name: ARGO_AUTOMATION_WORKFLOW_CPU_LIMIT
              value: "{{ .cpu }}"
            - name: ARGO_AUTOMATION_WORKFLOW_MEMORY_LIMIT
              value: "{{ .memory }}"
            {{- end }}
            {{- with .automationResources.requests }}
            - name: ARGO_AUTOMATION_WORKFLOW_CPU_REQUEST
              value: "{{ .cpu }}"
            - name: ARGO_AUTOMATION_WORKFLOW_MEMORY_REQUEST
              value: "{{ .memory }}"
            {{- end }}
            {{- end }}
            {{- with .argoWorkflows }}
            - name: PIPELINE_SERVICE_CLIENT_ENDPOINT
              value: "{{ .endpoint }}"
            - name: ARGO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argowf-client-token
                  key: token
            - name: ARGO_SECONDS_AFTER_COMPLETION_TTL
              value: "{{ .secondsAfterCompletionTTL }}"
            - name: ARGO_SERVER_CERTIFICATE_PATH
              value: "{{ .certificatePath }}"
            - name: ARGO_TEST_CONNECTION_BACKOFF_TIME
              value: "{{ .backoffTime }}"
            {{- end }}
            {{- end }}        
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
