apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybrid-ingestion-agent.fullname" . }}
  labels:
    {{- include "hybrid-ingestion-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: app
  selector:
    {{- include "hybrid-ingestion-agent.selectorLabels" . | nindent 4 }}
