name: Create release branch
run-name: Create release branch for ${{ inputs.release_branch_name }}
on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: "Release branch name"
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-branch:
    name: Create release branch ${{ inputs.release_branch_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Update application version
      working-directory: charts/hybrid-ingestion-runner
      run: |
        sed -i "s/$(cat ../../.version)/${{ inputs.release_branch_name}}/g" ../../README.md ../../.version Chart.yaml values.yaml
    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        title: 'chore(release): Prepare ${{ inputs.release_branch_name }} release'
        body: |
          - Update application version to `${{ inputs.release_branch_name }}`
        branch: "release/${{ inputs.release_branch_name }}"
        commit-message: 'chore(release): Prepare Branch for release ${{ inputs.release_branch_name }}'
